### PR TITLE
Apply black 21.5b1 onto codebase

### PR DESCRIPTION
**Pull request by JulianWgs**
- black is a code formater support by the Python software foundation
- Many popular packages like pandas use it
- It ends all debate about code formatting. There are no settings to
configure.

https://github.com/psf/black

I'm not proposing this to be merged directly as I would take ownership
(via git blame) of all those changes. Rather I would like the main
contributors to apply black to their parts of the code base (black
<path>).

### CODE REVIEW

**Review by MicK7 — APPROVED** [review]

**Comment by MicK7** [comment]
Thanks for suggesting "black". Maybe adding adding a "blacken" github action would be a good option.

**Comment by MicK7** [comment]
autoblack action created

**Comment by JulianWgs** [comment]
The action only works for new code though. I would actually go ahead and retroactively convert the old code while leaving this pull request open to show the progress. I think black is a great tool and looking at the code base the code formatting is not consistent and mostly does not adhere to best practices.

**Comment by MicK7** [comment]
@JulianWgs The github action has updated the whole repository too. I agree that the code is far from best practices.

**Comment by JulianWgs** [comment]
Ah great! Well then my script I've worked on is probably useless. It should only black lines with a specific author email address. I didn't test it thoroughly :D You can check it out here. Might be of interest for other project where every author blacks his or her own lines.

https://gist.github.com/JulianWgs/ba762ba729d8f17090cafd5230261ab2

**Pull request closed without merging**
