### PR TITLE
Use relative path to CGNS logo README

### PR DESCRIPTION
**Pull request by JulianWgs**
- was broken, because of master to main rename

### CODE REVIEW

**Review by MicK7 — APPROVED** [review]

**Comment by MicK7** [comment]
Thanks for the feedback

**Comment by MicK7** [comment]
LGTM

**Comment by MicK7** [comment]
@JulianWgs Can you do the  merge  ?

**Comment by JulianWgs** [comment]
No, I don't have commit access

**Comment by MicK7** [comment]
Sorry. I don't know why the auto merge did not activate after the approval.
I will have to ask Marc about how he has setup the access.

Commit merged

**Comment by JulianWgs** [comment]
Why did you close the pull request and then merge the changes? Why didnt you merge the the pull request directly 😊

**Comment by MicK7** [comment]
I thought that merging locally would preserve the commit author while the github setup would have modified it.
By the if you have a small commit to add, I would be interested to check if the auto-merge does not activate again.

**Pull request closed without merging**
